{
 "title": "Démos LogQL",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Nombre de logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (service_name) (count_over_time({service_name=\"nginx_paris_1\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Ips des clients",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (remote_addr) (count_over_time({service_name=\"nginx_paris_1\"} | json [$__range]))",
     "legendFormat": "{{ remote_addr }}"
    }
   ]
  },
  {
   "title": "Requests status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (status) (count_over_time({service_name=\"nginx_paris_1\"}[1m] | json ))",
     "legendFormat": "{{ status }}"
    }
   ]
  }
 ]
}