{
 "title": "TP3",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Main stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app6_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Users online %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (app6_users_count_online / app6_users_count_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de capteurs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count({__name__ =~ \"app6_sensors_sensor.*_temp_degrees\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de métriques",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count({__name__ =~ \"app6_.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lantency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app6_requests_latency_seconds", "legendFormat": "__auto" }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app6_users_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 6 },
   "targets": [
    { "expr": "app6_users_count_new", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Online users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app6_users_count_online", "legendFormat": "__auto" }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "irate(app6_errors_total[1m])", "legendFormat": "A" },
    { "expr": "irate(app6_requests_total[1m])", "legendFormat": "B" },
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Sensors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{__name__ =~ \"app6_sensors_sensor(.+)_temp_degrees\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Sensor 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app6_sensors_sensor1_temp_degrees",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sensor 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app6_sensors_sensor2_temp_degrees",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sensor 3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app6_sensors_sensor3_temp_degrees",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}