##############################################################
# Vagrant file for the lab                                   #
##############################################################
Vagrant.configure("2") do |base|      

  ##############################################################
  # Base                                                       #
  ##############################################################
  base.vm.box = "debian/bookworm64"

  base.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "2"
  end

  base.vm.provision "shell", inline: <<-RUN_AS_ROOT
    apt update
	  apt install -y nginx vim zsh curl figlet git ca-certificates gnupg lsb-release build-essential      
	  curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
	  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt update
	  apt install -y docker-ce docker-ce-cli containerd.io    
	  usermod -aG docker vagrant    
    chsh -s /bin/zsh vagrant
    cp /vagrant/daemon.json /etc/docker/daemon.json
    systemctl restart docker.service
  RUN_AS_ROOT
  
  base.vm.provision "shell", privileged: false, inline: <<-RUN_AS_VAGRANT
    git clone https://github.com/robbyrussell/oh-my-zsh.git --depth 1 --single-branch ~/.oh-my-zsh
    cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc    
    sed -i 's/_THEME=\"robbyrussell\"/_THEME=\"agnoster\"/g' .zshrc
    sed -i 's/plugins=(git)/plugins=(git docker kubectl minikube)/g' .zshrc
  RUN_AS_VAGRANT

  ##############################################################
  # Grafana + Loki + Tempo                                     #
  ##############################################################  
  base.vm.define "main" do |main|
    main.vm.network "private_network", ip: "192.168.56.10"
    main.vm.hostname = "main"

    main.vm.provision "shell", inline: <<-MAIN
	    figlet main > /etc/motd
    MAIN
  end

end

